require 'spec_helper'

RSpec.describe PrimeMultiplier::NumberGenerator do
  subject do
    described_class.new
  end

  context 'when primes are generated by valid num' do
    let(:num_primes) { 10 }
    let(:only_primes) { subject.call(num_primes).any? { |num| prime?(num) } }

    it { expect(subject.call(num_primes)).to be_an Array }
    it { expect(subject.call(num_primes).length).to eq num_primes }
    it { expect(only_primes).to be true }
  end

  context 'when invalid number is used' do
    let(:num_primes) { 0 }

    it { expect(subject.call(num_primes)).to be_an Array }
    it { expect(subject.call(num_primes)).to be_empty }
  end
end
